### ISSUE TITLE
Align to Nodejs LTS

### ISSUE THREAD

**Issue by UlisesGascon** [yeoman/generator-chrome-extension#233]
Some of our dependencies require a higher minimal Nodejs version. See #224 

**Current Nodejs LTS version:**

![image](https://user-images.githubusercontent.com/5110813/161748596-ecfb882a-ac0b-4239-8915-adc1ccf65792.png)

**Action items:**
- [x] ~~Anchor dependencies versions~~ #235
- [x] ~~Add `package-lock.json`~~ #236 
- [x] ~~Remove compatibility with versions 6 to 10 in pkg and CI~~ #234
- [x] ~~Add compatibility with 12,14,16 and 17 in pkg and CI~~ #234
